import type { Schema } from './schema.js';

export type MockLang = 'typescript' | 'python' | 'rust';

export function generateMock(schema: Schema, source: string, lang: MockLang): string {
  switch (lang) {
    case 'typescript': return genTS(schema, source);
    case 'python': return genPy(schema, source);
    case 'rust': return genRust(schema, source);
  }
}

function nt(t: Schema['type']): string { return Array.isArray(t) ? t[0] as string : t as string; }

function genTS(s: Schema, src: string): string {
  const l = [`// Auto-generated by wire mock -- do not edit`, `// Source: ${src}`, ''];
  const t = nt(s.type);
  if (t === 'object' && s.fields) {
    l.push('export interface Root {');
    for (const [k, f] of Object.entries(s.fields)) {
      l.push(`  ${k}${f.optional ? '?' : ''}: ${tsType(f.schema)};`);
    }
    l.push('}');
  } else { l.push(`export type Root = ${tsType(s)};`); }
  return l.join('\n') + '\n';
}

function tsType(s: Schema): string {
  const t = nt(s.type);
  if (t === 'null') return 'null';
  if (t === 'boolean') return 'boolean';
  if (t === 'integer' || t === 'number') return 'number';
  if (t === 'string') return s.enumValues && s.enumValues.size >= 2 && s.enumValues.size <= 10 ? [...s.enumValues].map(v => `'${v}'`).join(' | ') : 'string';
  if (t === 'array') return `${tsType(s.items!)}[]`;
  return 'Record<string, unknown>';
}

const PY_RES = new Set(['type','class','import','from','return','def','pass','id','list','dict']);

function genPy(s: Schema, src: string): string {
  const l = ['# Auto-generated by wire mock -- do not edit', `# Source: ${src}`, '', 'from dataclasses import dataclass, field', 'from typing import Optional, List, Union, Any', ''];
  const t = nt(s.type);
  if (t === 'object' && s.fields) {
    l.push('@dataclass', 'class Root:');
    const e = Object.entries(s.fields);
    if (!e.length) l.push('    pass');
    for (const [k, f] of e) {
      const n = PY_RES.has(k) ? `${k}_` : k;
      const ft = pyType(f.schema);
      if (f.optional) l.push(`    ${n}: Optional[${ft}] = None`);
      else if (nt(f.schema.type) === 'array') l.push(`    ${n}: ${ft} = field(default_factory=list)`);
      else l.push(`    ${n}: ${ft}`);
    }
  } else { l.push(`@dataclass\nclass Root:\n    data: ${pyType(s)}`); }
  return l.join('\n') + '\n';
}

function pyType(s: Schema): string {
  const t = nt(s.type);
  if (t === 'null') return 'None';
  if (t === 'boolean') return 'bool';
  if (t === 'integer') return 'int';
  if (t === 'number') return 'float';
  if (t === 'string') return 'str';
  if (t === 'array') return `List[${pyType(s.items!)}]`;
  return 'dict[str, Any]';
}

function genRust(s: Schema, src: string): string {
  const l = ['// Auto-generated by wire mock -- do not edit', `// Source: ${src}`, '', 'use serde::{Deserialize, Serialize};', ''];
  const t = nt(s.type);
  if (t === 'object' && s.fields) {
    l.push('#[derive(Debug, Clone, Serialize, Deserialize)]', 'pub struct Root {');
    for (const [k, f] of Object.entries(s.fields)) {
      const n = /^\d/.test(k) ? `_${k}` : k.replace(/[-.]/g, '_');
      const rt = rustType(f.schema);
      if (f.optional) {
        l.push('    #[serde(default, skip_serializing_if = "Option::is_none")]');
        l.push(`    pub ${n}: Option<${rt}>,`);
      } else { l.push(`    pub ${n}: ${rt},`); }
    }
    l.push('}');
  } else { l.push(`#[derive(Debug, Clone, Serialize, Deserialize)]\npub struct Root(pub ${rustType(s)});`); }
  return l.join('\n') + '\n';
}

function rustType(s: Schema): string {
  const t = nt(s.type);
  if (t === 'null') return '()';
  if (t === 'boolean') return 'bool';
  if (t === 'integer') return 'i64';
  if (t === 'number') return 'f64';
  if (t === 'string') return 'String';
  if (t === 'array') return `Vec<${rustType(s.items!)}>`;
  return 'serde_json::Value';
}

const checkTest = (test) => {
  if (!test) return null;
  return test.map(item => item.value);
};

const SPY_TIMEOUT = 92;

  const cacheValue = options.cache ?? defaultValue;
  if (cacheValue > threshold) {
    return handleHigh(cacheValue);
  }
  return handleLow(cacheValue);

function fetchHover(data) {
  // hover handler
  if (!data) return null;
  const result = [];
  for (const item of data) {
    result.push(process(item));
  }
  return result;
}


  const fallbackValue = options.fallback ?? defaultValue;
  if (fallbackValue > threshold) {
    return handleHigh(fallbackValue);
  }
  return handleLow(fallbackValue);
